using Unity.VisualScripting;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{
    [Header("References")]
    public PlayerMovementStats MoveStats;
    [SerializeField] private Collider2D feetCollider;
    [SerializeField] private Collider2D bodyCollider;
    [SerializeField] private Animator playerAnim;
    [SerializeField] private GameObject character;
    [SerializeField] private float gapBetweenTimelines = 200f;

    private int currentTimeline = 0;


    public Rigidbody2D rb { get; private set; }

    //movement vars
    private Vector2 moveVelocity;
    private bool isFacingRight;
    
    private bool onMovingPlatform;


    //collision vars
    private RaycastHit2D groundHit;
    private RaycastHit2D headHit;
    private bool isGrounded;
    private bool bumpedHead;

    // jump vars
    public float VerticalVelocity { get; private set; }
    private bool isJumping;
    private bool isFastFalling;
    private bool isFalling;
    private float fastFallTime;
    private float fastFallReleaseSpeed;
    private int numberOfJumpsUsed;

    // apex vars
    private float apexPoint;
    private float timePastApexThreshold;
    private bool isPastApexThreshold;

    // jump buffer vars
    private float jumpBufferTimer;
    private bool jumpReleasedDuringBuffer;

    // coyote time vars
    private float coyoteTimer;


    private void Awake()
    {
        isFacingRight = true;
        rb = GetComponent<Rigidbody2D>();
    }

    private void Update()
    {
        CountTimers();
        JumpChecks();
        changeTimeLines();
    }

    private void FixedUpdate()
    {
        CollisionChecks();
        Jump();

        if(isGrounded)
        {
            Move(MoveStats.groundAcceleration, MoveStats.groundDeceleration, InputMenager.movement);
        }
        else
        {
            Move(MoveStats.airAcceleration, MoveStats.airDeceleration, InputMenager.movement);
        }
        
        playerAnim.SetFloat("Speed",Mathf.Abs(InputMenager.movement.x));
    }

    private void Move(float acceleration, float deceleration, Vector2 moveInput) 
    {
        TurnCheck(moveInput);
        if (moveInput != Vector2.zero)
        {
            moveVelocity = Vector2.Lerp(moveVelocity,new Vector2(moveInput.x,0f)* MoveStats.maxWalkSpeed,acceleration*Time.fixedDeltaTime);
        }
        else
        {
            moveVelocity = Vector2.Lerp(moveVelocity, Vector2.zero, deceleration * Time.fixedDeltaTime);
          
        }
        rb.linearVelocity = new Vector2(moveVelocity.x, rb.linearVelocity.y);

    }

    private void TurnCheck(Vector2 moveInput)
    {
        if (isFacingRight && moveInput.x < 0) 
        {
            Turn(false);
        }
        else if (!isFacingRight && moveInput.x > 0)
        {
            Turn(true);
        }
    }
    private void Turn(bool turnRight)
    {
        if (turnRight)
        {
            isFacingRight = true;
            transform.Rotate(0f, 180f, 0);
        }
        else
        {
            isFacingRight = false;
            transform.Rotate(0f, -180f, 0);
        }
    }

    private void CheckIfGrounded()
    {
        Vector2 boxCastOrigin = new Vector2(feetCollider.bounds.center.x, feetCollider.bounds.min.y);
        Vector2 boxCastSize = new Vector2(feetCollider.bounds.size.x, MoveStats.groundDetectionRayLenght);

        groundHit = Physics2D.BoxCast(boxCastOrigin, boxCastSize, 0f, Vector2.down, MoveStats.groundDetectionRayLenght, MoveStats.groundLayer);
        if(groundHit.collider)
        {
            isGrounded = true;
        }
        else
        {
            isGrounded = false;
        }

        
    }
    
    private void CheckIfHeadHitCeli()
    {
        Vector2 boxCastOrigin = new Vector2(bodyCollider.bounds.center.x, bodyCollider.bounds.max.y);
        Vector2 boxCastSize = new Vector2(bodyCollider.bounds.size.x/2, MoveStats.headDetectionRayLenght);

        groundHit = Physics2D.BoxCast(boxCastOrigin, boxCastSize, 0f, Vector2.up, MoveStats.headDetectionRayLenght, MoveStats.groundLayer);
        if(groundHit.collider)
        {
            bumpedHead = true;
        }
        else
        {
            bumpedHead = false;
        }
    }

    private void CollisionChecks() 
    {
        CheckIfGrounded();
        CheckIfHeadHitCeli();
    }

    private void Jump()
    {
        if (isJumping)
        {
            if (bumpedHead)
            {
                isFastFalling = true;
            }
        }

        if(VerticalVelocity >= 0f)
        {
            apexPoint = Mathf.InverseLerp(MoveStats.InitialJumpVelocity, 0f, VerticalVelocity);
            if(apexPoint > MoveStats.ApexThreshold)
            {
                if(!isPastApexThreshold)
                {
                    isPastApexThreshold = true;
                    timePastApexThreshold = 0f;
                }
                if (isPastApexThreshold)
                {
                    timePastApexThreshold += Time.fixedDeltaTime;
                    if(timePastApexThreshold < MoveStats.ApexHangTime)
                    {
                        VerticalVelocity = 0f;
                    }
                    else
                    {
                        VerticalVelocity = -0.01f;
                    }
                }
            }
            else
            {
                VerticalVelocity += MoveStats.Gravity * Time.fixedDeltaTime;
                if (isPastApexThreshold)
                {
                    isPastApexThreshold = false;
                }
            }
        }
        else if (!isFastFalling)
        {
            VerticalVelocity += MoveStats.Gravity * MoveStats.GravityOnReleaseMultiplier * Time.fixedDeltaTime;
        }
        else
        {
            if(!isFalling)
            {
                isFalling = true;
            }
        }
        
        if (isFastFalling)
        {
            if(fastFallTime >= MoveStats.TimeForUpwardsCancel)
            {
                VerticalVelocity += MoveStats.Gravity * MoveStats.GravityOnReleaseMultiplier * Time.fixedDeltaTime;
            }else if (fastFallTime < MoveStats.TimeForUpwardsCancel)
            {
                VerticalVelocity = Mathf.Lerp(fastFallReleaseSpeed, 0f, (fastFallTime / MoveStats.TimeForUpwardsCancel));
            }
            fastFallTime += Time.fixedDeltaTime;
        }
        if(!isGrounded && !isJumping)
        {
            if (!isFalling)
            {
                isFalling = true;
            }
            VerticalVelocity += MoveStats.Gravity * Time.fixedDeltaTime;

        }
        VerticalVelocity = Mathf.Clamp(VerticalVelocity, -MoveStats.MaxFallSpeed, 50f);
        rb.linearVelocity = new Vector2 (rb.linearVelocity.x, VerticalVelocity);
    }

    private void JumpChecks()
    {
        if (InputMenager.jumpWasPressed)
        {
            jumpBufferTimer = MoveStats.JumpBufferTime;
            jumpReleasedDuringBuffer = false;
        }

        if (InputMenager.jumpWasReleased)
        {
            if(jumpBufferTimer > 0f)
            {
                jumpReleasedDuringBuffer = true;
            }
            if(isJumping && VerticalVelocity > 0f)
            {
                isPastApexThreshold = false;
                isFastFalling = true;
                fastFallTime = MoveStats.TimeForUpwardsCancel;
                VerticalVelocity = 0f;
            }
            else
            {
                isFastFalling = true;
                fastFallReleaseSpeed = VerticalVelocity;
            }
        }

        if(jumpBufferTimer > 0f && !isJumping && (isGrounded || coyoteTimer > 0f))
        {
            InitiateJump(1);
            if (jumpReleasedDuringBuffer)
            {
                isFastFalling = true;
                fastFallReleaseSpeed = VerticalVelocity;
            }
        }
        else if (jumpBufferTimer > 0f && isJumping && numberOfJumpsUsed < MoveStats.NumberOfJumpsAllowed)
        {
            InitiateJump(1);
            isFastFalling = false;
        }
        else if (jumpBufferTimer > 0f && isFalling && numberOfJumpsUsed < MoveStats.NumberOfJumpsAllowed - 1)
        {
            InitiateJump(2);
            isFastFalling = false;
        }

        if((isJumping || isFalling) && isGrounded && VerticalVelocity <= 0f)
        {
            isJumping = false;
            isFalling = false;
            isFastFalling = false;
            fastFallTime = 0f;
            isPastApexThreshold = false;
            numberOfJumpsUsed = 0;
            VerticalVelocity = Physics2D.gravity.y;
        }

    }

    private void InitiateJump(int _numberOfJumpsUsed)
    {
        if (!isJumping)
        {
            isJumping = true;
        }
        jumpBufferTimer = 0f;
        numberOfJumpsUsed += _numberOfJumpsUsed;
        VerticalVelocity = MoveStats.InitialJumpVelocity;
    }


    private void CountTimers()
    {
        jumpBufferTimer -= Time.deltaTime;

        if (!isGrounded)
        {
             coyoteTimer -= Time.deltaTime;
        }
        else
        {
            coyoteTimer = MoveStats.JumpCoyoteTime;
        }
    }

    private void changeTimeLines()
    {
        if (InputMenager.timeChangeFutuPressed && currentTimeline != 1)
        {
            //animacja
            int changeValue = 1 - currentTimeline;
            transform.SetPositionAndRotation(new Vector3(transform.position.x, transform.position.y + gapBetweenTimelines * changeValue, transform.position.z),transform.rotation); 
            currentTimeline = 1;
        }else if (InputMenager.timeChangePresPressed && currentTimeline != 0)
        {
            //animacja
            int changeValue = -currentTimeline;
            transform.SetPositionAndRotation(new Vector3(transform.position.x, transform.position.y + gapBetweenTimelines * changeValue, transform.position.z),transform.rotation); 
            currentTimeline = 0;
        }else if (InputMenager.timeChangePastPressed && currentTimeline != -1)
        {
            //animacja
            int changeValue = currentTimeline - 1;
            transform.SetPositionAndRotation(new Vector3(transform.position.x, transform.position.y + gapBetweenTimelines * changeValue, transform.position.z),transform.rotation); 
            currentTimeline = -1;
        }
    }
    
    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Moving") && transform.parent != collision.transform)
        {
            transform.SetParent(collision.transform, true); // Attach to platform, preserving position
        }
    }

    private void OnCollisionExit2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Moving") && transform.parent != null)
        {
            transform.SetParent(null); // Detach from platform
        }
    }

}
